version: "3"

services: 
  app:
    build: .
    command: npm start
    ports: 
      - "3000:3000"
    volumes: 
      - .:/usr/app

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
